export const VERSION = '2.0.0-dev'
export { SGNode } from './node'
export type { SGContext, SGNodeInit, Agg, CmpInfo } from './node'
export { Supergroup } from './collection'
export type { BackEdge } from './collection'
export { supergroup, groupLevel, regroupNode } from './group'
export type { GroupOpts } from './group'
export { normalizeDims } from './dims'
export type { DimAccessor, DimSpec, DimInput, NormalDim, SGNodeLike } from './dims'
export { recordsFor, recordsUnder } from './selection'
